"""water level unit conversion

Revision ID: 0dc9eeb97575
Revises: e5328ed85676
Create Date: 2026-09-14 09:36:25.975341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dc9eeb97575'
down_revision: Union[str, Sequence[str], None] = 'e5328ed85676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'water_level_settings',
        sa.Column(
            'water_level_unit',
            sa.Enum('METRIC', 'IMPERIAL', name='waterlevelunit'),
            nullable=False,
            server_default='METRIC',
            comment="Unit in which water levels are retrieved. Either 'METRIC' (meters) or 'IMPERIAL' (feet).",
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('water_level_settings', 'water_level_unit')
    # ### end Alembic commands ###
