"""remove home_folder from disk_management

Revision ID: 589efafcb60f
Revises: 3b7b3a2b8d08
Create Date: 2025-08-15 15:50:01.512483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '589efafcb60f'
down_revision: Union[str, Sequence[str], None] = '3b7b3a2b8d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disk_management', 'home_folder')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disk_management', sa.Column('home_folder', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
