"""move remote site id to callback_url model

Revision ID: b084946ad874
Revises: cdad732405a1
Create Date: 2025-11-14 11:37:47.471303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import Integer, select, update

# revision identifiers, used by Alembic.
revision: str = 'b084946ad874'
down_revision: Union[str, Sequence[str], None] = 'cdad732405a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the remote_site_id column to the callback_url table
    op.add_column(
        "callback_url",
        sa.Column(
            "remote_site_id",
            sa.Integer,
            nullable=True,
            comment="Remote site ID used to upload videos and time series",
        ),
    )
    # Reflect the settings table
    settings_table = table(
        "settings",
        column("remote_site_id", Integer),
    )

    # Reflect the callback_url table
    callback_url_table = table(
        "callback_url",
        column("id", Integer),
        column("remote_site_id", Integer),
    )


    # Get the remote_site_id from the settings table
    connection = op.get_bind()
    remote_site_id = connection.execute(select(settings_table.c.remote_site_id)).scalar()

    if remote_site_id is not None:
        # Update the first record in the callback_url table with the remote_site_id
        connection.execute(
            update(callback_url_table).where(callback_url_table.c.id == 1).values(remote_site_id=remote_site_id)
        )

    # Drop the remote_site_id column from the settings table
    op.drop_column("settings", "remote_site_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
