"""custom service and service parameter

Revision ID: b8cc02017430
Revises: 1e2f8592d51d
Create Date: 2026-02-27 15:15:48.695585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8cc02017430'
down_revision: Union[str, Sequence[str], None] = '1e2f8592d51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_short_name', sa.String(length=255), nullable=False),
    sa.Column('service_long_name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.Enum('ONE_TIME', 'TIMER', name='servicetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('readme', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('update_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_service_short_name'), 'service', ['service_short_name'], unique=True)
    op.create_index(op.f('ix_service_service_type'), 'service', ['service_type'], unique=False)
    op.create_table('service_parameter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('parameter_short_name', sa.String(length=255), nullable=False),
    sa.Column('parameter_long_name', sa.String(length=255), nullable=False),
    sa.Column('parameter_type', sa.Enum('BOOLEAN', 'INTEGER', 'FLOAT', 'STRING', 'LITERAL', name='parametertype'), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_parameter_parameter_type'), 'service_parameter', ['parameter_type'], unique=False)
    op.create_index(op.f('ix_service_parameter_service_id'), 'service_parameter', ['service_id'], unique=False)
    op.create_index(op.f('ix_video_config_sync_status'), 'video_config', ['sync_status'], unique=False)

    # add a JSON field to time series for miscellaneous ts information
    op.add_column('time_series', sa.Column('misc', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_config_sync_status'), table_name='video_config')
    op.drop_index(op.f('ix_service_parameter_service_id'), table_name='service_parameter')
    op.drop_index(op.f('ix_service_parameter_parameter_type'), table_name='service_parameter')
    op.drop_table('service_parameter')
    op.drop_index(op.f('ix_service_service_type'), table_name='service')
    op.drop_index(op.f('ix_service_service_short_name'), table_name='service')
    op.drop_table('service')

    # remove JSON field from time series
    op.drop_column('time_series', 'misc')
    # ### end Alembic commands ###
    # ### end Alembic commands ###
