"""callback_url column for max timeout

Revision ID: cdad732405a1
Revises: 2374087cd4d0
Create Date: 2025-10-08 09:24:05.367855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdad732405a1'
down_revision: Union[str, Sequence[str], None] = '2374087cd4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('callback_url', sa.Column('retry_timeout', sa.Float(), server_default="0", nullable=False, comment='Maximum time to repeatedly try requests to api. If set to zero, only one try will be attempted.'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('callback_url', 'timeout')
    # ### end Alembic commands ###
